name: Mock CI

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "mock"
  pull_request:
    paths:
      - "mock"

permissions: {}

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check formatting
        run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Clippy check
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings
